apiVersion: v1
kind: Pod
metadata:
  name: myconfig
spec:
  containers:
  - name: c2
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo hellooo; sleep 5 ; done"]
    env:
    - name: MYENV
      valueFrom:
        configMapKeyRef:
          name: myconf
          key: sample.conf