kind: Pod
apiVersion: v1
metadata:
  name: demolabel
  labels:
    env: development
    class: pods
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Vasu; sleep 5 ; done"]