apiVersion: v1
kind: Pod
metadata:
  name: mysec
spec:
  containers:
  - name: c3
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo hello; sleep 5 ; done"]
    volumeMounts:
    -  name: testsecret
       mountPath: "/temp/secrets"
  volumes:
  - name: testsecret
    secret:
      secretName: mysecret